@startuml Forza 4
Class "ClientTCP" {
    +ClientTCP(serverIp, serverPort)

    -connection
    -input
    -output
    +serverResponse
}

class "Game" {
    +Game(graphic, clientTCP)

    +state
    +graphic
    +playGround
    +currentPlayerName
    +clientTCP
    +requestAtServer
}

class "Graphic" {
    +Graphic()

    -buttonConnectedPressed
    -buttonDisconnectedPressed
    -buttonPawnPressed
    +buttonPawnPressedY
    +buttonPawnPressedX
    -lobbyFrame
    -waitingFrame
    -playGroundFrame
    -disconnectFrame
    -winnerFrame
    -finishFrame
}

class "Pawn" {
    +Pawn()
    +Pawn(color, positionX, positionY)

    +color
    +positionX
    +positionY
}

class "PlayGround" {
    +PlayGround()

    +colums
    +rows
    +pawns[][]
}

class "RequestAtServer" {
    +RequestAtServer()

    +command
    +positionX
}
@enduml