@startuml Forza 4
Class "ClientThread" {
    +ClientThread()
    +ClientThread(clientSocket)

    -clientSocket
}

class "Player" {
    +Player()
    +Player(name)

    +name
    +isLogged
}

class "Game" {
    +Game()

    +state
    +playGround
    +player1
    +player2
    +turn

    +
}

class "PlayGround" {
    +PlayGround()

    +pawns[]
    +colums
    +rows
}

class "Pawn" {
    +Pawn()
    +Pawn(color)

    +color
    +positionX
    +positionY
}

Class "Client" {
    -port
    -ip

    +getPort()
    +setPort()
    +getIp()
    +setiIp()
}

Class "Server" {
    -port
    -ip

    +getPort()
    +setPort()
    +getIp()
    +setiIp()
}

User -- Client
User -- Server
@enduml