@startuml Forza 4
class "User" {
    +Persona(nome, cognome)

    -name
    -logged
    -
    
    +getNome()
    +setNome()
    +getCognome()
    +setiCognome()
}

class "Game" {
    +
}

class "PlayGround" {

}

class "Pawn" {

}

Class "Client" {
    -port
    -ip

    +getPort()
    +setPort()
    +getIp()
    +setiIp()
}

Class "Server" {
    -port
    -ip

    +getPort()
    +setPort()
    +getIp()
    +setiIp()
}

User -- Client
User -- Server
@enduml